server:
  port: 18040

spring:
  application:
    name: gateway
  cloud:
    gateway:
      api-prefix:
      discovery:
        locator:
          #是否与服务发现组件进行结合,通过service-id(必须设置成大写)转发到具体的服务实例。默认false
          #为true代表开启基于服务发现的路由规则。
          enabled: true
          #配置之后访问时service-id无需大写
          lower-case-service-id: true
#      # 单实例路由， 不注册到eureka
#      routes:
#        - id: consumer
#          uri: http://localhost:18020
#          predicates:
#            - Path=/service-consumer/**
#          filters:
#            - StripPrefix=1
      routes:
        - id: consumer
          uri: lb://service-consumer
          predicates:
            - Path=/consumer/**
#          filters:
#            - StripPrefix=1
        - id: provider
          uri: lb://service-provider
          predicates:
            - Path=/user/**
#          filters:
#            - StripPrefix=1


eureka:
  instance:
    hostname: gateway
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    metadata-map:
      cluster: main
  client:
    service-url:
      defaultZone: http://eureka-serverA:18001/eureka/,http://eureka-serverB:18002/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info"

info:
  author: org
  book: kmjs
  project: service gateway demo
