#server:
#  port: 18001
#spring:
#  application:
#    name: eureka-server
#eureka:
#  instance:
#    hostname: eureka-server
##    lease-renewal-interval-in-seconds: 30
#    instance-id: ${spring.cloud.client.Address}:${server.port}
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    region: kmjs
#    availability-zones:
#      kmjs: map_eureka
#    service-url:
#      map_eureka: http://192.168.2.18:18001/eureka/,http://192.168.2.19:18001/eureka/
  #    service-url:
#      defaultZone: http://localhost:18001/eureka
#  server:
#    enable-self-preservation: true
#    renewal-percent-threshold: 0.49
