server:
  port: 18001
spring:
    application:
      name: eureka-server-cluster
eureka:
  instance:
    hostname: eureka-serverA
#    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-serverB:18002/eureka
#      defaultZone: http://eureka-serverA:18001/eureka
#  server:
#    enable-self-preservation: true
#    renewal-percent-threshold: 0.49
