server:
  port: 18001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:18001/eureka
      # 默认值是true
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.49
