server:
  port: 18010
spring:
  application:
    name: service-provider
eureka:
  instance:
    hostname: service-provider
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-serverA:18001/eureka,http://eureka-serverB:18002/eureka

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info"

info:
  author: org
  book: kmjs
  project: service provider demo