server:
  port: 18010
spring:
  application:
    name: service-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kmjs_springboot?characterEncoding=utf-8
    username: root
    password: .J;/;vqXe2ic
mybatis:
  type-aliases-package: org.kmjs.springcloudserviceprovider.*.model
  mapper-locations: classpath:/mybatis/sqlmap/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
eureka:
  instance:
    hostname: service-provider
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    metadata-map:
      cluster: main
  client:
    service-url:
      defaultZone: http://eureka-serverA:18001/eureka,http://eureka-serverB:18002/eureka
#    fetch-registry: false
#    register-with-eureka: false

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, hystrix.stream"

info:
  author: org
  book: kmjs
  project: service provider demo

hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
  threadpool:
    default:
      coreSize: 20
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 2000
          thread:
            timeoutInMilliseconds: 2000